In [1]:
#Question 5

In [2]:
##Import and load packages

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
!pip install sklearn

Requirement already satisfied: sklearn in c:\users\user\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\users\user\anaconda3\lib\site-packages (from sklearn) (0.24.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.20.1)
Requirement already satisfied: joblib>=0.11 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.6.2)

In [55]:
df = pd.read_csv('2007.csv')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2007,1,1,1,1232.0,1225,1341.0,1340,WN,2891,...,4,11,0,NaN,0,0,0,0,0,0
1,2007,1,1,1,1918.0,1905,2043.0,2035,WN,462,...,5,6,0,NaN,0,0,0,0,0,0
2,2007,1,1,1,2206.0,2130,2334.0,2300,WN,1229,...,6,9,0,NaN,0,3,0,0,0,31
3,2007,1,1,1,1230.0,1200,1356.0,1330,WN,1355,...,3,8,0,NaN,0,23,0,0,0,3
4,2007,1,1,1,831.0,830,957.0,1000,WN,2278,...,3,9,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7453210,2007,12,15,6,1558.0,1605,1749.0,1736,DL,58,...,14,17,0,NaN,0,0,0,0,0,0
7453211,2007,12,15,6,1902.0,1851,2110.0,2105,DL,59,...,6,21,0,NaN,0,0,0,0,0,0
7453212,2007,12,15,6,1024.0,1025,1750.0,1735,DL,61,...,14,19,0,NaN,0,0,0,15,0,0
7453213,2007,12,15,6,1353.0,1315,1658.0,1622,DL,62,...,11,14,0,NaN,0,0,0,0,0,36
7453214,2007,12,15,6,1824.0,1800,2001.0,1928,DL,63,...,10,26,0,NaN,0,24,0,9,0,0

In [14]:
df4 = pd.read_csv("2006.csv")
df4

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2006,1,11,3,743.0,745,1024.0,1018,US,343,...,45,13,0,NaN,0,0,0,0,0,0
1,2006,1,11,3,1053.0,1053,1313.0,1318,US,613,...,27,19,0,NaN,0,0,0,0,0,0
2,2006,1,11,3,1915.0,1915,2110.0,2133,US,617,...,4,11,0,NaN,0,0,0,0,0,0
3,2006,1,11,3,1753.0,1755,1925.0,1933,US,300,...,16,10,0,NaN,0,0,0,0,0,0
4,2006,1,11,3,824.0,832,1015.0,1015,US,765,...,27,12,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7141917,2006,12,29,5,1246.0,1249,1452.0,1459,DL,1675,...,6,12,0,NaN,0,0,0,0,0,0
7141918,2006,12,29,5,1225.0,1155,2033.0,1931,DL,1676,...,12,35,0,NaN,0,30,0,32,0,0
7141919,2006,12,29,5,2118.0,2115,2254.0,2241,DL,1676,...,9,27,0,NaN,0,0,0,0,0,0
7141920,2006,12,29,5,2122.0,2127,2209.0,2223,DL,1677,...,5,21,0,NaN,0,0,0,0,0,0
7141921,2006,12,29,5,2042.0,2045,2213.0,2235,DL,1678,...,5,15,0,NaN,0,0,0,0,0,0

In [17]:
from sklearn.metrics import plot_roc_curve
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier  # added classification model
from sklearn.gaussian_process.kernels import RBF # added classification model
from sklearn.svm import LinearSVC  # added classification model
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer #transform different types

In [12]:
##Pre-processing stage

In [15]:
###for numerical features

In [23]:
numerical_features = ['DepDelay', 'ArrDelay']

#applying SimpleImputer and StandardScaler into a pipeline
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('scaler', StandardScaler())])
numerical_features
numerical_transformer

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler())])

In [19]:
##for categorical features

In [24]:
categorical_features = ['FlightNum', 'Month', 'DayOfMonth']

#applying SimpleImputer and then OneHotEncoder into another pipeline
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])
categorical_features
categorical_transformer

Pipeline(steps=[('imputer', SimpleImputer()),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [25]:
data_transformer = ColumnTransformer(
    transformers=[
        ('numerical', numerical_transformer, numerical_features),
        ('categorical', categorical_transformer, categorical_features)])
data_transformer

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['DepDelay', 'ArrDelay']),
                                ('categorical',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['FlightNum', 'Month', 'DayOfMonth'])])

In [ ]:
##merged pipeline now contains all the pre-processing steps, and can be used as starting point for different learners

In [44]:
#Now ready to complete machine learning pipeline by attaching a learner to the pipeline from above
pipe_lr = Pipeline(steps=[('data_transformer', data_transformer),
                         ('pipe_lr', LogisticRegression(max_iter=1000000))])
pipe_lr

Pipeline(steps=[('data_transformer',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['DepDelay', 'ArrDelay']),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['FlightNum', 'Month',
                                                   'DayOfMonth'])])),
                ('pipe_lr', LogisticRegression(max_iter=1000000))])

In [56]:
def get_delay_counts(df):
    grp = df.groupby(['DepDelay', 'ArrDelay'])['DayofMonth', 'Month'].nunique()
    return {key: grp[key] for key in list(grp.keys())}
def get_delay_proportions(df):
    delay_counts = get_delay_counts(df)
    return {val[0]: round(val[1]/df.shape[0], 4) for val in delay_counts.items()}

print("Dataset delay counts", get_delay_counts(df))
print("Dataset delay proportions", get_delay_proportions(df))

<ipython-input-56-fcdf88f4b4eb>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  grp = df.groupby(['DepDelay', 'ArrDelay'])['DayofMonth', 'Month'].nunique()

Dataset delay counts {'DayofMonth': DepDelay  ArrDelay
-305.0    -312.0      1
-169.0     8.0        1
-168.0    -13.0       1
-165.0    -175.0      1
          -162.0      1
                     ..
 1689.0    1665.0     1
 1736.0    1715.0     1
 1831.0    1848.0     1
 1956.0    1942.0     1
 2601.0    2598.0     1
Name: DayofMonth, Length: 52347, dtype: int64, 'Month': DepDelay  ArrDelay
-305.0    -312.0      1
-169.0     8.0        1
-168.0    -13.0       1
-165.0    -175.0      1
          -162.0      1
                     ..
 1689.0    1665.0     1
 1736.0    1715.0     1
 1831.0    1848.0     1
 1956.0    1942.0     1
 2601.0    2598.0     1
Name: Month, Length: 52347, dtype: int64}
Dataset delay proportions {'DayofMonth': DepDelay  ArrDelay
-305.0    -312.0      0.0
-169.0     8.0        0.0
-168.0    -13.0       0.0
-165.0    -175.0      0.0
          -162.0      0.0
                     ...
 1689.0    1665.0     0.0
 1736.0    1715.0     0.0
 1831.0    1848.0     0.0
 1956.0    1942.0     0.0
 2601.0    2598.0     0.0
Name: DayofMonth, Length: 52347, dtype: float64, 'Month': DepDelay  ArrDelay
-305.0    -312.0      0.0
-169.0     8.0        0.0
-168.0    -13.0       0.0
-165.0    -175.0      0.0
          -162.0      0.0
                     ...
 1689.0    1665.0     0.0
 1736.0    1715.0     0.0
 1831.0    1848.0     0.0
 1956.0    1942.0     0.0
 2601.0    2598.0     0.0
Name: Month, Length: 52347, dtype: float64}

In [72]:
##split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df, 
                                                    test_size=0.5, 
                                                    random_state=1)

ValueError: not enough values to unpack (expected 4, got 2)

In [40]:
##to tune the pipeline, we can use grid search cross-validation using GridSearchCV()

In [1]:
#hyperparameters are set using separated parameter names
param_grid = {
    'data_transformer__numerical__imputer__strategy': ['mean', 'median'],
    'data_transformer__categorical__imputer__syrategy': ['constant', 'most_frequent']
}

grid_lr = GridSearchCV(pipe_lr, param_grid=param_grid)

grid_lr.fit(X_train, y_train);

NameError: name 'GridSearchCV' is not defined

In [ ]:
##compare two machine learning pipelines using plot ROC 

ax = plt.gca()

plot_roc_curve(grid.lr, X_test, y_test, ax=ax, name='Logistic Regression')
plot_roc_curve(grid_gdb, X_test, y_test, ax=ax, name='Gradient Boosting')

plt.show()